-- ===============================================
-- PROYECTO: PetCare
-- SCRIPT: Creación y carga inicial de tabla COMIDA_GATITO
-- OBJETIVO: Registrar las comidas diarias de los gatitos.
-- ===============================================


-- ===============================================
-- 🐱 CREACIÓN DE TABLA
-- ===============================================

-- Creamos la tabla principal que almacenará los registros
-- de alimentación de cada gatito, con su respectiva hora,
-- tipo de comida, responsable y fecha de registro.
CREATE TABLE COMIDA_GATITO (
    ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Identificador único autogenerado.
    NOMBRE_GATITO VARCHAR2(100) NOT NULL,                   -- Nombre del gatito.
    HORA_COMIDA TIMESTAMP NOT NULL,                         -- Hora exacta de la comida.
    TIPO_COMIDA VARCHAR2(50),                               -- Tipo de comida (croquetas, atún, etc.)
    RESPONSABLE VARCHAR2 (100),                             -- Persona encargada de alimentar al gatito.
    FECHA_REGISTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP       -- Fecha y hora en que se registró el dato.
);

-- ===============================================
-- 📘 COMENTARIOS DESCRIPTIVOS DE LA TABLA Y COLUMNAS
-- ===============================================

COMMENT ON TABLE COMIDA_GATITO IS 'Tabla que almacena los registros de las horas de comida de los gatitos.';
COMMENT ON COLUMN COMIDA_GATITO.ID IS 'Identificador único del registro.';
COMMENT ON COLUMN COMIDA_GATITO.NOMBRE_GATITO IS 'Nombre del gatito que pertenece al registro.';
COMMENT ON COLUMN COMIDA_GATITO.HORA_COMIDA IS 'Hora exacta en la que se alimentó al gatito.';
COMMENT ON COLUMN COMIDA_GATITO.TIPO_COMIDA IS 'Tipo de comida que se le da al gatito (croquetas, atún, pollito).';
COMMENT ON COLUMN COMIDA_GATITO.RESPONSABLE IS 'Nombre del cuidador responsable del registro.';
COMMENT ON COLUMN COMIDA_GATITO.FECHA_REGISTRO IS 'Fecha y hora en que se realizó el registro automáticamente.';

-- Guardamos los cambios estructurales.
COMMIT;


-- ===============================================
-- 🔍 CONSULTA DE VERIFICACIÓN
-- ===============================================
-- Consulta básica para verificar que la tabla fue creada correctamente.
SELECT * FROM COMIDA_GATITO;


-- ===============================================
-- 🍽️ INSERCIÓN DE DATOS DE EJEMPLO
-- ===============================================

-- Registro 1: Michi comió a las 08:00 croquetas con Ana como responsable.
INSERT INTO COMIDA_GATITO (NOMBRE_GATITO, HORA_COMIDA, TIPO_COMIDA, RESPONSABLE)
VALUES ('Michi', TO_TIMESTAMP('08:00:00', 'HH24:MI:SS'), 'Croquetas', 'Ana');

-- Registro 2: Pelusa comió a las 12:30 pescado, alimentado por Carlos.
INSERT INTO COMIDA_GATITO (NOMBRE_GATITO, HORA_COMIDA, TIPO_COMIDA, RESPONSABLE)
VALUES ('Pelusa', TO_TIMESTAMP('12:30:00', 'HH24:MI:SS'), 'Pescado', 'Carlos');

-- Registro 3: Nieve tomó leche a las 07:30 con Laura como responsable.
INSERT INTO COMIDA_GATITO (NOMBRE_GATITO, HORA_COMIDA, TIPO_COMIDA, RESPONSABLE)
VALUES ('Nieve', TO_TIMESTAMP('07:30:00', 'HH24:MI:SS'), 'Leche', 'Laura');

-- Registro 4: Bigotes comió pollo a las 18:00, alimentado por Miguel.
INSERT INTO COMIDA_GATITO (NOMBRE_GATITO, HORA_COMIDA, TIPO_COMIDA, RESPONSABLE)
VALUES ('Bigotes', TO_TIMESTAMP('18:00:00', 'HH24:MI:SS'), 'Pollo', 'Miguel');

-- Registro 5: Luna comió croquetas premium a las 21:00, con Sofía responsable.
INSERT INTO COMIDA_GATITO (NOMBRE_GATITO, HORA_COMIDA, TIPO_COMIDA, RESPONSABLE)
VALUES ('Luna', TO_TIMESTAMP('21:00:00', 'HH24:MI:SS'), 'Croquetas premium', 'Sofía');

-- Guardamos todos los registros insertados.
COMMIT;
